// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name"`
}

type Response struct {
	Message string `json:"message"`
}

type RequestJson struct {
	Name string `json:"name"`
}
